# █░█░█ █ █▄░█ █▀▄ █▀█ █░█░█   █▀█ █░█ █░░ █▀▀ █▀
# ▀▄▀▄▀ █ █░▀█ █▄▀ █▄█ ▀▄▀▄▀   █▀▄ █▄█ █▄▄ ██▄ ▄█

# Opacity
windowrule = opacity 0.85 0.80, match:class ^(firefox)$
windowrule = opacity 0.80 0.80, match:class ^(code)$
windowrule = opacity 0.80 0.80, match:class ^(steam)$
windowrule = opacity 0.80 0.80, match:class ^(steamwebhelper)$
windowrule = opacity 0.80 0.80, workspace 5, match:class ^(Spotify)$
windowrule = opacity 0.90 0.90, match:title ^(nvim)$
windowrule = opacity 0.80 0.80, match:class ^(thunar)$
windowrule = opacity 0.80 0.80, match:class ^(file-roller)$
windowrule = opacity 0.80 0.80, match:class ^(nwg-look)$
windowrule = opacity 0.80 0.80, match:class ^(qt5ct)$
windowrule = opacity 0.80 0.80, match:class ^(discord)$ #Discord-Electron
windowrule = opacity 0.80 0.80, match:class ^(WebCord)$ #WebCord-Electron
windowrule = opacity 0.80 0.70, float on, match:class ^(pavucontrol)$
windowrule = opacity 0.80 0.70, float on, match:class ^(org.kde.polkit-kde-authentication-agent-1)$
windowrule = opacity 0.80 0.80, workspace 3, match:class ^(org.telegram.desktop)$

# Position
windowrule = float on, match:title ^(Media viewer)$
windowrule = float on, move (75) ((monitor_h*0.44)), size 800 600, match:title ^(Volume Control)$
windowrule = float on, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(Viewnior)$
windowrule = float on, match:title ^(DevTools)$
windowrule = float on, match:class ^(file_progress)$
windowrule = float on, match:class ^(confirm)$
windowrule = float on, match:class ^(dialog)$
windowrule = float on, size 800 600, match:class ^(download)$
windowrule = float on, match:class ^(notification)$
windowrule = float on, match:class ^(error)$
windowrule = float on, match:class ^(confirmreset)$
windowrule = float on, size 800 600, match:title ^(Open File)$
windowrule = float on, match:title ^(branchdialog)$
windowrule = float on, match:title ^(Confirm to replace files)
windowrule = float on, match:title ^(File Operation Progress)


# Workspace
windowrule = workspace 1, idle_inhibit fullscreen, match:class ^(Brave-browser)$
windowrule = workspace 2, match:class ^(discord)$
windowrule = workspace 4, match:class ^(Code)$
windowrule = workspace 4, match:class ^(code-url-handler)$

# Size
windowrule = size 800 600, match:title ^(Save File)$

windowrule = idle_inhibit focus, match:class ^(mpv)$

# xwaylandvideobridge
windowrule = opacity 0.0 override 0.0 override, no_anim on, no_focus on, no_initial_focus on, match:class ^(xwaylandvideobridge)$

windowrule = no_focus on, border_size 0, no_anim on, float on, match:class ^(eww)$



