exec-once = hyprpm reload -n
exec-once = waybar
exec-once = swaybg -i /home/giahoang/Pictures/.wallpapers/1213525.jpg -m fill
#exec-once = mako

exec-once = nm-applet &
exec-once =  blueman-applet &
exec-once = fcitx5 -d

exec-once = dunst
exec-once = ~/.config/hypr/scripts/now_playing.sh
