# Nạp các thành phần
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/programs.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/appearance.conf
source = ~/.config/hypr/keybinds.conf
source = ~/.config/hypr/rules.conf

# Tự động nạp plugin và dịch vụ
exec-once = hyprpm reload -n
exec-once = waybar & hyprpaper
