$mainMod = SUPER
# Phím tắt Scroller
bind = $mainMod, left, scroller:movefocus, l
bind = $mainMod, right, scroller:movefocus, r

# Ứng dụng
bind = $mainMod, Q, exec,ghostty
bind = $mainMod, E, exec, wofi --show drun
