windowrule = opacity 0.9 0.7, match:class ^(firefox)$
windowrule = opacity 0.9 0.7, match:class ^(antigravity)$
windowrule = opacity 0.9 0.7, match:class ^(code)$
windowrule = opacity 0.9 0.5, match:class ^(org\.kde\.dolphin)$
